// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbc4ohTa2MvdEt2hG-NquJMxUTfkreTtQ',
    appId: '1:585672454269:web:48f3ac3165ba96c100c114',
    messagingSenderId: '585672454269',
    projectId: 'test-63c23',
    authDomain: 'test-63c23.firebaseapp.com',
    storageBucket: 'test-63c23.appspot.com',
    measurementId: 'G-TW8HWY3RB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoZkkGQFZHKrYeXmxM98hJcZKtzNxjxpw',
    appId: '1:585672454269:android:83d8ab3cfaad71a200c114',
    messagingSenderId: '585672454269',
    projectId: 'test-63c23',
    storageBucket: 'test-63c23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy8LmKAWXsspYx0BQtqiTiIECmkzQsQSM',
    appId: '1:585672454269:ios:6c1d15e6020b2b2b00c114',
    messagingSenderId: '585672454269',
    projectId: 'test-63c23',
    storageBucket: 'test-63c23.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy8LmKAWXsspYx0BQtqiTiIECmkzQsQSM',
    appId: '1:585672454269:ios:6c1d15e6020b2b2b00c114',
    messagingSenderId: '585672454269',
    projectId: 'test-63c23',
    storageBucket: 'test-63c23.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbc4ohTa2MvdEt2hG-NquJMxUTfkreTtQ',
    appId: '1:585672454269:web:6471e77838fcc1aa00c114',
    messagingSenderId: '585672454269',
    projectId: 'test-63c23',
    authDomain: 'test-63c23.firebaseapp.com',
    storageBucket: 'test-63c23.appspot.com',
    measurementId: 'G-517535FSYW',
  );
}
